In [5]:
import numpy as np

my_arr = np.arange(1000000)
my_list = list(range(1000000))
%time for _ in range(10):my_arr2 = my_arr*2

Wall time: 5 ms
Wall time: 31.7 ms


In [4]:
%time for _ in range(10):my_list2 = [x*2 for x in my_list]

Wall time: 1.22 s


In [7]:
import numpy as np

data = np.random.randn(2,3)
data

array([[ 0.48534087, -1.16331267,  1.41146695],
       [ 1.06063012,  0.47336558, -0.36524581]])

In [8]:
data*10

array([[  4.85340866, -11.63312668,  14.11466953],
       [ 10.60630119,   4.73365576,  -3.65245806]])

In [9]:
data + data 

array([[ 0.97068173, -2.32662534,  2.82293391],
       [ 2.12126024,  0.94673115, -0.73049161]])

In [12]:
print(data)
data.shape

[[ 0.48534087 -1.16331267  1.41146695]
 [ 1.06063012  0.47336558 -0.36524581]]


(2, 3)

In [11]:
data.dtype

dtype('float64')

In [13]:
data1 = [6,7.5,8,0,1]

arr1 = np.array(data1)
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [14]:
data2 = [[1,2,3,4],[5,6,7,8]]

arr2 = np.array(data2)
arr2


array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [15]:
arr2.ndim#数组轴的个数，也被称作秩

2

In [16]:
arr2.shape

(2, 4)

In [17]:
arr1.dtype

dtype('float64')

In [18]:
arr2.dtype

dtype('int32')

In [21]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [22]:
np.zeros((3,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [23]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [29]:
np.empty((2,3,2))

array([[[1.22776728e-311, 3.16202013e-322],
        [0.00000000e+000, 0.00000000e+000],
        [0.00000000e+000, 4.03396549e+175]],

       [[9.77741349e+165, 5.39715484e-066],
        [1.47742725e-075, 4.50291150e-033],
        [2.64471824e+180, 1.51245198e+160]]])

In [30]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [33]:
arr = np.array([1,2,3,4,5])
arr.dtype

dtype('int32')

In [35]:
float_arr = arr.astype(np.float64)
float_arr.dtype
float_arr

array([1., 2., 3., 4., 5.])

In [36]:
numeric_strings = np.array(['1.25','-9.6','42'],dtype=np.string_)

numeric_strings.astype(float)

array([ 1.25, -9.6 , 42.  ])

In [37]:
int_array = np.arange(10)
calibers = np.array([.22,.270,.357,.380,.44,.50],dtype=np.float64)
int_array.astype(calibers.dtype)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])